export enum SCREENS {
  APP_STACK = 'APP_STACK',
  BOTTOM_TABS = 'BOTTOM_TABS',
  LANDING = 'LANDING',
  SIGN_UP = 'SIGN_UP',
  SING_IN = 'SING_IN',
  HOME = 'HOME',
  PROFILE = 'PROFILE',
  DISCOVER = 'DISCOVER',
}
